### ISSUE TITLE
Taro 3.5.1版本无法使用

### ISSUE THREAD

**Issue by yanbowe** [pcdotfan/taro-plugin-tailwind#121]
![image](https://user-images.githubusercontent.com/43030980/182277056-0f18fdf7-7bba-4318-b817-fccc1148decf.png)

**Comment by pcdotfan** [comment]
已复现，您可以暂时先通过在项目中安装 `postcss-loader` 的方式解决此问题

```
npm i -D postcss-loader
```

**Comment by yanbowe** [comment]
> 已复现，您可以暂时先通过在项目中安装 `postcss-loader` 的方式解决此问题
> 
> ```
> npm i -D postcss-loader
> ```

收到，谢谢
