### ISSUE TITLE
Taro3.5.3 使用webpack5编译报错

### ISSUE THREAD

**Issue by Vinsurs** [pcdotfan/taro-plugin-tailwind#131]
Taro3.5.3 使用webpack5编译报错， 使用React（v18）框架，taro-plugin-tailwind最新版本,  报错如下:

  
![1661177445(1)](https://user-images.githubusercontent.com/48487732/185944379-e896e5f7-1603-4de4-b9af-eef988910d43.png)
~~~~
请问这个问题要怎么解决呢？

**Comment by pcdotfan** [comment]
目前不支持 `webpack5`（使用的 `postcss-loader` 版本不同），如果有好的解决方案可以 PR 哈。
