### ISSUE TITLE
为何会生成出一个 .\!visible 的类名

### ISSUE THREAD

**Issue by yuuk** [pcdotfan/taro-plugin-tailwind#145]
项目里面没有使用 !visible 的 className，为啥生成出来的文件会出现  .\!visible 的类名

![Snipaste_2022-09-14_22-03-58](https://user-images.githubusercontent.com/9426456/190175975-86da5cb8-7945-4b90-904c-973eb10dc9a3.jpg)

**Comment by towry** [comment]
我的项目莫名出现一个 .tab\.label 的东西，很奇怪。

**Comment by towry** [comment]
换用了 https://github.com/dcasia/mini-program-tailwind
