### ISSUE TITLE
小程序需要重新 build 才能生效， h5 报错

### ISSUE THREAD

**Issue by zysam** [pcdotfan/taro-plugin-tailwind#16]
根据文档安装了插件，发现如下问题：

1. 安装插件后，小程序运行正常，但是开发模式，实时预览是不生效的。需要在命令行重新运行 `npm run dev:weapp`
2.  本来是想， h5 实时预览会正常，运行 `npm run dev:h5` 会直接报错
```
🙅   Failed to compile.

  Error: Child compilation failed:
  Module parse failed: Unexpected token (1:0)
  File was processed with these loaders:
   * ./node_modules/html-webpack-plugin/lib/loader.js
   * ./node_modules/windicss-webpack-plugin/dist/loaders/transform-template.js
  You may need an additional loader to handle the result of these loaders.
  > <!DOCTYPE html>
  | <html>
  | <head>:
  SyntaxError: Unexpected token (1:0)

```

**Comment by pcdotfan** [comment]
可以尝试一下 `v1.1.2` 版本或者试试示例项目能否跑得起来，如果仍有问题还请再反馈哈

**Comment by zysam** [comment]
> 可以尝试一下 `v1.1.2` 版本或者试试示例项目能否跑得起来，如果仍有问题还请再反馈哈

请问你在开发模式下，修改 tailwindcss 样式，能正常编译不？我的只有启动时正常，修改后编译（或热加载）都不行。用 ` DEBUG=*wind* npm run dev:weapp` debug 信息如下：

```
监听文件修改中...

undefined Write virtual module: ../client/@virtual/windi.css /* windicss-hmr(invalid: ../src/pages/index/index.tsx):2 */
undefined Emit file change: ../client/@virtual/windi.css 1615884393050
```

**Comment by pcdotfan** [comment]
暂时设置 `NODE_ENV` 为 `production` 解决问题，例：`NODE_ENV=production npm run build:weapp -- --watch`，具体参见示例。
我还没搞懂为什么 `production` 可以，会跟进的。

**Comment by zysam** [comment]
> 暂时设置 `NODE_ENV` 为 `production` 解决问题，例：`NODE_ENV=production npm run build:weapp -- --watch`，具体参见示例。
> 我还没搞懂为什么 `production` 可以，会跟进的。

很感谢你的回复。我升级后，问题1 解决了。 问题2，h5 问题我找到原因，原来 `config/index.js` 上
```
plugins: [
    ['taro-plugin-tailwind', {
      scan: {
          dirs: ['./src'], // 只扫描 src 目录下的文件
          exclude: ['dist/**/*'], // 排除 dist 目录
      },
      // 具体参数见：https://github.com/windicss/vite-plugin-windicss/blob/main/packages/plugin-utils/src/options.ts#L10
  }] 
  ],
```
如过写上这个配置， h5 会报错，只能写 `'taro-plugin-tailwind'`。你可以查查，是否是配置冲突？如果是可以修改下 readme，不然会误导。

**Comment by pcdotfan** [comment]
好的 我更新下哈
