### ISSUE TITLE
安装了没有提示，也没有效果

### ISSUE THREAD

**Issue by protogenesis** [pcdotfan/taro-plugin-tailwind#18]
按照文档步骤安装后，添加 CSS 类名然后重新运行项目没有效果。
使用提供的示例代码运行也报错：
```
yarn dev:weapp                               
yarn run v1.22.5
$ NODE_ENV=production npm run build:weapp -- --watch
'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
```
info:
OS: WIN 10
taro: 3.1.4
taro-plugin-tailwind: "^1.1.2"

**Comment by pcdotfan** [comment]
漏了 `cross-env`，麻烦重新拉一下项目试试示例哈。

**Comment by protogenesis** [comment]
重新拉取示例代码并运行，没有报错，但是 tailwindcss 样式好像没有打包进 app.wxss，导致类名无效
![image](https://user-images.githubusercontent.com/32860504/111728846-b0fa2980-88a8-11eb-9e6e-b6ca2e114a1e.png)

**Comment by pcdotfan** [comment]
可以试一下 `v1.1.3` 版本

**Comment by protogenesis** [comment]
谢谢！
taro-plugin-tailwind 换成 ```1.1.3``` 就可以了
