### ISSUE TITLE
小数点单位的类名运行报错

### ISSUE THREAD

**Issue by protogenesis** [pcdotfan/taro-plugin-tailwind#19]
你好，刚发现类名无法使用小数点。
使用小数点后小程序会报错：

```index.js```:

![image](https://user-images.githubusercontent.com/32860504/111898492-56f09400-8a61-11eb-83f1-4ca073487f63.png)

编译后的  ```app.wxss```:

![image](https://user-images.githubusercontent.com/32860504/111898501-68d23700-8a61-11eb-9e55-fa62ba267720.png)

报错信息：

![image](https://user-images.githubusercontent.com/32860504/111898489-4cce9580-8a61-11eb-83b0-93dfd6d1a6ed.png)

Info:
👽 Taro v3.1.4
"taro-plugin-tailwind": "^1.1.3"

**Comment by aihanjiao** [comment]
怎么说呢，Text是行内元素，你设置margin-top没用的

解决办法：
1、暂时在块级元素写mt-3-5（不知道啥时候能解决）
![image](https://user-images.githubusercontent.com/59612542/115330937-911b9580-a1c7-11eb-9188-1067f9053c99.png)
效果：
![image](https://user-images.githubusercontent.com/59612542/115330944-94af1c80-a1c7-11eb-980c-46510b8f900e.png)
为什么不能用mt-3.5之类的语法呢？
1、会报错；
2、报错就不说了，更重要的是编译后.会丢失；
![image](https://user-images.githubusercontent.com/59612542/115331116-e9eb2e00-a1c7-11eb-8ab9-14d98a827323.png)
![image](https://user-images.githubusercontent.com/59612542/115331123-ebb4f180-a1c7-11eb-86ec-3f420118777e.png)
![image](https://user-images.githubusercontent.com/59612542/115331126-ed7eb500-a1c7-11eb-87cc-768bed6e792a.png)
变成3了

**Comment by pcdotfan** [comment]
因为小程序不支持 `class` 里出现 `/` `.` 这样的特殊字符，比较好的方法可能是看看之后能不能支持 windicss 的 [Compliation Mode](https://windicss.org/guide/modes.html#compilation-mode)，目前我暂时没办法解决哈😅

**Comment by protogenesis** [comment]
收到，谢谢
