### ISSUE TITLE
1.3版本 Vue3 应该怎样配置呢？似乎不生效

### ISSUE THREAD

**Issue by DaZiYuan** [pcdotfan/taro-plugin-tailwind#197]
测试代码
[master.zip](https://github.com/pcdotfan/taro-plugin-tailwind/files/10891443/master.zip)

**Comment by DaZiYuan** [comment]
忘记改这了
```shell
  content: ["./src/**/*.{js,tx,vue}"],
```

**Comment by pcdotfan** [comment]
感谢反馈

**Comment by DaZiYuan** [comment]
> 感谢反馈

昨天测试高度似乎也没生效，暂时退回1.2.8了
例如:`h-100,sm:xx,lg:xx`
