### ISSUE TITLE
taro3.6.10，tailwind样式不生效

### ISSUE THREAD

**Issue by BaoXianSheng** [pcdotfan/taro-plugin-tailwind#230]
按照readme一步一步配置的，样式不生效。没有报错，请求帮助
[hooks-demo.zip](https://github.com/pcdotfan/taro-plugin-tailwind/files/12178918/hooks-demo.zip)

**Comment by pcdotfan** [comment]
你的配置文件里有 typo，`/page/` 应该是 `/pages/`。

**Comment by BaoXianSheng** [comment]
> typo
抱歉我提交的源文件有问题，但我觉这不是主要原因，我并不是没有试过加上pages，是无效的。我刚才又重新试了一遍，结果是一样的

**Comment by BaoXianSheng** [comment]
我甚至尝试了content: [
    "./src/pages/**/*.{js,tx,tsx,jsx,vue}",
    "./src/**/*.{js,tx,tsx,jsx,vue}",
  ]，每个文件都加了

**Comment by BaoXianSheng** [comment]
要放在css里

**Comment by pcdotfan** [comment]
看起来在 webpack5 上有些问题，我今晚回去试试看
