### ISSUE TITLE
 您好，现在taro已经在git上发不了4.04版本，我用了您的插件发现不支持，您如果有空能更新一下对4.x版本的支持吗

### ISSUE THREAD

**Issue by Ka0fKa** [pcdotfan/taro-plugin-tailwind#234]

**Comment by pcdotfan** [comment]
可以 晚些操作

**Comment by Ka0fKa** [comment]
> 可以 晚些操作

非常感谢您的付出，因为我看到官方在这方面并没有动作，您的框架真是及时雨，主要是用了tailwindcss真不想再去写一堆CSS类名了，然后再次感谢您的付出，祝您生活愉快万事顺意!

**Comment by waynessa** [comment]
https://github.com/pcdotfan/taro-plugin-tailwind/tree/main/example

升级后看起来可以正常使用，参考这个示例

**Comment by pcdotfan** [comment]
https://github.com/pcdotfan/taro-plugin-tailwind/tree/main/example

升级后看起来可以正常使用，可以参考这个示例
