### ISSUE TITLE
添加taro-plugin-tailwind之后会导致h5 tabbar样式错误

### ISSUE THREAD

**Issue by shuigedeng** [pcdotfan/taro-plugin-tailwind#28]
1. 环境 
  "taro-plugin-tailwind": "^1.1.6",
   "@tarojs/taro": "3.2.1",
   "taro-ui": "^3.0.0-alpha.3",
2. 结果
3. 
![image](https://user-images.githubusercontent.com/26796592/115642817-2b382680-a30b-11eb-8f48-5113df07ead1.png)

**Comment by pcdotfan** [comment]
已经复现了，原因是我默认排除了 `dist/` 目录下的扫描导致 `weui` 等样式不能正常加载，下载 `1.1.7` 版本重试或者手动复写配置：
```
{ exclude: [] }
```
