### ISSUE TITLE
看上去不工作

### ISSUE THREAD

**Issue by swaitw** [pcdotfan/taro-plugin-tailwind#3]
使用后，在app.wxss中只是原样输出了 
@tailwind base;
@tailwind utilities;
****

**Comment by pcdotfan** [comment]
能否提供一下简单的复现步骤？

**Comment by pcdotfan** [comment]
试试 [v1.0.6](https://github.com/pcdotfan/taro-plugin-tailwind/releases/tag/v1.0.6) 😅 犯了个低级错误
