### ISSUE TITLE
bug h-full类没有编译

### ISSUE THREAD

**Issue by Visualizeit** [pcdotfan/taro-plugin-tailwind#35]
taro项目版本：3.2.8
下面的示例中 h-full没有编译 ,w-full编译正常
![image](https://user-images.githubusercontent.com/61679509/117970060-ca749a80-b35a-11eb-8040-45ebbbaeec68.png)
![image](https://user-images.githubusercontent.com/61679509/117970097-da8c7a00-b35a-11eb-915e-b410dae9f0ab.png)

**Comment by pcdotfan** [comment]
是配置漏写了 `full` 的问题，已经在 `v1.2.1` 修复
