### ISSUE TITLE
自定义 tabBar 无法生效

### ISSUE THREAD

**Issue by Qinruiy** [pcdotfan/taro-plugin-tailwind#36]
# 问题描述
app.config.js 启用 tabBar:{custom:true}后
在 src/custom-tab-bar/index.jsx中样式不生效

**Comment by Visualizeit** [comment]
我在开发自定义tarbar的时候也遇见了这个问题，但我发现我自定义的css类tarbar组件也没有应用，查了文档发现是因为小程序的自定义组件有样式隔离，默认无法应用全局样式。
解决办法是在自定义tarbar的根组件原型上添加一个options = {
    addGlobalClass: true,
}
```tsx
import type { FC } from '@tarojs/taro'
import { Nav } from './featrue'

const TabBar: FC = () => {
    return (
        <>
            <Nav />
        </>
    )
}

TabBar.options = {
    addGlobalClass: true,
}

export default TabBar

```
