### ISSUE TITLE
taro3.0.18尝试失败

### ISSUE THREAD

**Issue by pialin** [pcdotfan/taro-plugin-tailwind#4]
你好，我在taro项目中尝试了这个插件 但是编译后tailwind的样式并没有生效，看到编译后的app.wxss并没有包含tailwind的类。所以怀疑tailwindcss没有被处理打包。具体操作步骤如下：
1.npm install taro-plugin-tailwind --save-dev
2.引入插件
3.taro tailwind --init生成配置文件
4.src中创建tailwind.src.css文件
5.参数配置（这一步没做！！！）；
6.在组件的classname中添加tailwindcss的类；
7.npm run build:weapp
除了参数配置之外都与README一致，也不清楚启动这个插件还需要什么其他配置。麻烦指导一下@pcdotfan， 感谢！

**Comment by pcdotfan** [comment]
我晚点起一个示例代码哈😄 第一次写这种估计都是 bug

**Comment by pialin** [comment]
> 我晚点起一个示例代码哈😄 第一次写这种估计都是 bug，见谅见谅

@pcdotfan 非常感谢你的回复，我尝试了example，编译之后还是报错
```
[ WXSS 文件编译错误] ./app.wxss
 unexpected token ";"
> 1 | @tailwind base;
    |               ^
  2 | @tailwind components;
  3 | @tailwind utilities;
  4 | 
```
我觉得应该是postcss缺少了tailwindcss，所以又在config/index.js加了
```
...
  mini: {
    postcss: {
      tailwindcss: {
        enable: true
      },
...
```
但还是报错
```
[ WXSS 文件编译错误] ./app.wxss
 unexpected "\" at pos 22511
  943 | }
  944 | 
> 945 | .space-y-0\.5 > :not([hidden]) ~ :not([hidden]) {
      |          ^
  946 |   --tw-space-y-reverse: 0;
  947 |   margin-top: calc(0.125rem * calc(1 - var(--tw-space-y-reverse)));
  948 |   margin-bottom: calc(0.125rem * var(--tw-space-y-reverse));
```
不能带反斜杠，看来css转wxss还是有挺多不兼容的地方要去掉的。。。

**Comment by pcdotfan** [comment]
> [ WXSS 文件编译错误] ./app.wxss
>  unexpected "\" at pos 22511
>   943 | }
>   944 | 
> > 945 | .space-y-0\.5 > :not([hidden]) ~ :not([hidden]) {
>       |          ^
>   946 |   --tw-space-y-reverse: 0;
>   947 |   margin-top: calc(0.125rem * calc(1 - var(--tw-space-y-reverse)));
>   948 |   margin-bottom: calc(0.125rem * var(--tw-space-y-reverse));
> ```
> 
> 不能带反斜杠，看来css转wxss还是有挺多不兼容的地方要去掉的。。。

是的，很多东西没法用，得再想想办法



> > 我晚点起一个示例代码哈😄 第一次写这种估计都是 bug，见谅见谅
> 
> @pcdotfan 非常感谢你的回复，我尝试了example，编译之后还是报错
> 
> ```
> [ WXSS 文件编译错误] ./app.wxss
>  unexpected token ";"
> > 1 | @tailwind base;
>     |               ^
>   2 | @tailwind components;
>   3 | @tailwind utilities;
>   4 | 
> ```

这个我再调查下 感谢反馈

**Comment by JimmyLv** [comment]
![image](https://user-images.githubusercontent.com/4997466/102902045-5a4ba200-44a9-11eb-9c79-1dc34233884e.png)

我这儿也是有问题 😂

**Comment by pcdotfan** [comment]
> ![image](https://user-images.githubusercontent.com/4997466/102902045-5a4ba200-44a9-11eb-9c79-1dc34233884e.png)
> 
> 我这儿也是有问题 😂

小程序只支持 `::before` 和 `::after`，暂时没有好办法解决这个……只能先避开这种 class 了

**Comment by JimmyLv** [comment]
有没有办法把这部分 css 挪掉，或者识别出来？

**Comment by pialin** [comment]
> 有没有办法把这部分 css 挪掉，或者识别出来？
@pcdotfan @JimmyLv 
我移除了一些没法直接用的样式，单独弄了一个css，总算是生效了，虽然少了很多东西。感兴趣的话可以参考一下 [TailwindCssForWechatMiniProgarm](https://github.com/pialin/TailwindCssForWechatMiniProgarm)

**Comment by mlboy** [comment]
mark..

**Comment by mlboy** [comment]
> > ![image](https://user-images.githubusercontent.com/4997466/102902045-5a4ba200-44a9-11eb-9c79-1dc34233884e.png)
> > 我这儿也是有问题 😂
> 
> 小程序只支持 `::before` 和 `::after`，暂时没有好办法解决这个……只能先避开这种 class 了

是否考虑小程序，通过插件替换掉这些，

**Comment by pcdotfan** [comment]
> > > ![image](https://user-images.githubusercontent.com/4997466/102902045-5a4ba200-44a9-11eb-9c79-1dc34233884e.png)
> > > 我这儿也是有问题 😂
> > 
> > 
> > 小程序只支持 `::before` 和 `::after`，暂时没有好办法解决这个……只能先避开这种 class 了
> 
> 是否考虑小程序，通过插件替换掉这些，

我更新了 `mini.config.js` 文件可以看看，目前发现不支持的插件：

```
    corePlugins: {
        preflight: false,
        divideColor: false,
        divideOpacity: false,
        divideStyle: false,
        divideWidth: false,
        divideColor: false,
        space: false,
        placeholderColor: false,
        placeholderOpacity: false,
    },
```
