### ISSUE TITLE
space-y-2 不能用

### ISSUE THREAD

**Issue by transtone** [pcdotfan/taro-plugin-tailwind#48]
https://tailwindcss.com/docs/space

这个功能应该是 `tailwind / windicss` 的标准功能呀，但我看放在配置的 `corePlugin` 里头，而且设置成 `true` 也不生效。

如果要使用这个特性，需要怎么配置呢？

**Comment by pcdotfan** [comment]
微信小程序目前支持的 CSS 选择器非常有限，具体见 https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxss.html，`spacing` 的实现涉及到 `~` 选择器，所以没有办法使用哈

**Comment by transtone** [comment]
不是在小程序，是在 h5 的环境下。又被小程序拖累了。
