### ISSUE TITLE
为啥配置了separator,但是还是出现了下面这个奇怪的名字

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [pcdotfan/taro-plugin-tailwind#49]
0 |   padding-bottom: 1.25rem;
  251 | }
> 252 | .tab\.name {
      |    ^
  253 |   -moz-tab-size: 4;
  254 |     -o-tab-size: 4;
  255 |        tab-size: 4;

**Comment by pcdotfan** [comment]
方便的话可否开个复现的仓库？

**Comment by liuhuapiaoyuan** [comment]
好的 我试试

**Comment by liuhuapiaoyuan** [comment]
我跪了 应该是windi的bug，只要className以tab开头 就会被他catch住，进行操作，我有一个组件Tabbar，他的className都是以 tabbar_前缀，因此出现了问题

**Comment by liuhuapiaoyuan** [comment]
又复查了一遍，就是不能出现任何tab，哪怕是变量也不行。const tab = 1，这样也会错
