### ISSUE TITLE
webstorm提示

### ISSUE THREAD

**Issue by Charl0tter** [pcdotfan/taro-plugin-tailwind#54]
请问怎么才能添加webstorm的智能提示呢？webstorm插件已经安装了

**Comment by pcdotfan** [comment]
可以先用 https://plugins.jetbrains.com/plugin/15321-tailwind-css 代替，[WebStorm Intellisense](https://windicss.org/editors/webstorm.html)

**Comment by pcdotfan** [comment]
可能需要等插件官方来解决了……目前似乎 tailwindcss 最新版也没有办法让 WebStorm 的 Intellisense 正常工作。我根据现有的几个 issue 试出了临时的解决方案：`devDependencies` 添加 `"tailwindcss": "2.2.7"` （版本号需一致）。

可关注：
1. https://youtrack.jetbrains.com/issue/WEB-52401
2. https://youtrack.jetbrains.com/issue/WEB-42792
3. https://youtrack.jetbrains.com/issue/WEB-50369

**Comment by transtone** [comment]
https://www.jianshu.com/p/a5ce2edea8c0 
可以将依赖指定版本：`npm:@tailwindcss/postcss7-compat@2.1.0`

**Comment by transtone** [comment]
按照楼主提供的简书文章，安装 `yarn add tailwindcss@npm:@tailwindcss/postcss7-compat@2.1.0` 就可以提示了。
