### ISSUE TITLE
微信下带反斜杠的推导样式不可用

### ISSUE THREAD

**Issue by transtone** [pcdotfan/taro-plugin-tailwind#56]
https://cn.windicss.org/features/value-auto-infer.html

windicss的很重要功能，自动值推导，因为wxss不支持反斜杠而无法使用。比如 bg-[#eee]，

![image](https://user-images.githubusercontent.com/46688/133867180-d6f5d239-2af1-4fa6-9acf-d54060127189.png)

有什么方案没有？

ps：背景可以用 `bg-hex-eee` 来解决。但 important `!text-20px` 用不了很郁闷。

**Comment by pcdotfan** [comment]
🥲 本质上还是 wxss 不支持转义符的问题，`auto-infer` 以及其它有用到转义符的语法应该都是无解的。有其它解决方案的朋友可以讨论讨论。

**Comment by transtone** [comment]
通过webpack，将特定的字符转义呢，或者像处理 1/2 宽度一样，用特定字符代替原定字符？

**Comment by transtone** [comment]
https://github.com/dcasia/wechat-mini-program-tailwind

这个项目用了webpack处理，可以支持原始的windicss写法。

**Comment by pcdotfan** [comment]
感谢，我周末研究一下

**Comment by mefengl** [comment]
@transtone [](https://github.com/dcasia/wechat-mini-program-tailwind/issues/5)

**Comment by mefengl** [comment]
https://github.com/dcasia/wechat-mini-program-tailwind/issues/5
