### ISSUE TITLE
webpack-chain里plugin是undefined是为什么？

### ISSUE THREAD

**Issue by lenetzp** [pcdotfan/taro-plugin-tailwind#60]
this.store Map(3) {
  'init' => [Function (anonymous)],
  'plugin' => undefined,
  'args' => [ { scan: [Object], config: '.taro-plugin-tailwind/h5.config.js' } ]
}
TypeError: Cannot read property '__expression' of undefined
    at Object.toConfig (D:\fe\git\ltzx\wopingan\node_modules\webpack-chain\src\Plugin.js:46:38)
    at D:\fe\git\ltzx\wopingan\node_modules\webpack-chain\src\Config.js:125:61
    at Array.map (<anonymous>)
    at module.exports.toConfig (D:\fe\git\ltzx\wopingan\node_modules\webpack-chain\src\Config.js:125:40)
    at D:\fe\git\ltzx\wopingan\node_modules\@tarojs\webpack-runner\src\index.ts:130:38
    at Generator.next (<anonymous>)
    at fulfilled (D:\fe\git\ltzx\wopingan\node_modules\@tarojs\webpack-runner\dist\index.js:5:58)

**Comment by zct1989** [comment]
同样出现这个问题

**Comment by zct1989** [comment]
#61

**Comment by zct1989** [comment]
`plugin.toConfig()`时显示`plugin.store.plugin` 为 `undefined`

```
 store: Map(3) {
    'init' => [Function (anonymous)],
    'plugin' => undefined,
    'args' => [ [Object] ]
  },
  name: 'windicss-webpack-plugin',
  shorthands: [ 'init' ],
  init: [Function (anonymous)]
} 
```

**Comment by zct1989** [comment]
@pcdotfan 

#62 

https://github.com/pcdotfan/taro-plugin-tailwind/blob/75a17dcd785d7dc779c55a63ff7c55d5bb7b547a/src/chain.ts#L3

应该是更换`windicss-webpack-plugin`后引入的问题,修改后可以正常启动

**Comment by beysong** [comment]
windicss-webpack-plugin这个的问题，回退到1.4.10版本

**Comment by pcdotfan** [comment]
> @pcdotfan
> 
> #62
> 
> https://github.com/pcdotfan/taro-plugin-tailwind/blob/75a17dcd785d7dc779c55a63ff7c55d5bb7b547a/src/chain.ts#L3
> 
> 应该是更换`windicss-webpack-plugin`后引入的问题,修改后可以正常启动

感谢，可以尝试 `v.1.2.2` 版本。
