### ISSUE TITLE
请问在 Taro 中能使用 windicss 的 Attributify Mode 吗

### ISSUE THREAD

**Issue by bluescurry** [pcdotfan/taro-plugin-tailwind#63]
我在  windicss 配置了 `attributify: true`，但是在页面中并未生效，所以想问问是否支持

**Comment by pcdotfan** [comment]
不好意思，犯了个低级错误 😓 ……尝试一下 `v1.2.3` 版本

**Comment by bluescurry** [comment]
> 不好意思，犯了个低级错误 😓 ……尝试一下 `v1.2.3` 版本

我升级到了`v1.2.3`版本，遗憾的是并没有生效。我的代码如下：
```html
<View className="flex-1 flex flex-row items-center" border="rounded-20"></View>
```
生成的样式中并没有 border 的属性
![image](https://user-images.githubusercontent.com/19237129/143366985-76b76ee9-3587-4443-99a7-0e5c1a9482d5.png)

**Comment by pcdotfan** [comment]
再试一次新版本哈，需要注意的是只有 H5 下是支持的（微信小程序不支持 Attributify Mode 用到的 `[attr~=value]` 选择器）

**Comment by bluescurry** [comment]
> 再试一次新版本哈，需要注意的是只有 H5 下是支持的（微信小程序不支持 Attributify Mode 用到的 `[attr~=value]` 选择器）

好的，谢谢
