### ISSUE TITLE
windi.css 自定义shortcuts无效

### ISSUE THREAD

**Issue by yanbowe** [pcdotfan/taro-plugin-tailwind#64]
windi.css 自定义shortcuts无效

**Comment by yanbowe** [comment]
![image](https://user-images.githubusercontent.com/43030980/144693928-58db87a1-34bb-4493-92bd-157c31555974.png)
以上自定义的calss在页面中使用并没有作用

**Comment by pcdotfan** [comment]
npm registry 不知道为什么没有列出之前发的 `v1.2.4` 版本……我重新发了 `v1.2.5`，可以指定版本再试试看有没有问题。

**Comment by yanbowe** [comment]
> npm registry 不知道为什么没有列出之前发的 `v1.2.4` 版本……我重新发了 `v1.2.5`，可以指定版本再试试看有没有问题。

感谢，可以了 theme 设置也可以用了
