### ISSUE TITLE
使用 Vue 中的 transition  组件的时候编译错误

### ISSUE THREAD

**Issue by hejianghu** [pcdotfan/taro-plugin-tailwind#65]
如题，当使用 Vue 的 transition  组件的时候，transition 组件被识别成了一个 class ? 里面还自动关联了一些 CSS3 transition 的内容？盲猜是不是词法解析的问题？

![image](https://user-images.githubusercontent.com/75015513/144856452-57bc43d1-0b30-46e5-bb27-c079021b7305.png)

wxss 中多出了如下代码：

![image](https://user-images.githubusercontent.com/75015513/144856649-3195fd15-e033-48a9-8557-f9290405b82c.png)

最终导致编译通不过：

![image](https://user-images.githubusercontent.com/75015513/144856734-12145fb8-ef33-48cf-ae64-ff98708bbbd7.png)
麻烦大佬帮忙看一下呢，感谢！
---------------
版本信息
"@tarojs/taro": "3.3.15"
"vue": "2.6.14"
"taro-plugin-tailwind": "1.2.3"

**Comment by hejianghu** [comment]
请问大佬有预计修复的时间么？感谢回复

**Comment by Yorksh1re** [comment]
+1

**Comment by Yorksh1re** [comment]
最后的解决方案是：

```
// tailwind.config.js
module.exports = {
  ...
    corePlugins: {
        ...
        transitionProperty: false // 禁止transition
    }
}
```

**Comment by hejianghu** [comment]
感谢大佬！
