### ISSUE TITLE
taro在dev环境下watch文件自动编译时，修改class没有自动编译生成对应的 css

### ISSUE THREAD

**Issue by abcdsxg** [pcdotfan/taro-plugin-tailwind#7]
开发环境经常需要调样式，比如我新加了个 class
![image](https://user-images.githubusercontent.com/20315934/106247725-e55b4d00-624a-11eb-89ff-c1c01e758314.png)

改完自动编译完成并不能立刻生效，重新运行才会自动生成
![image](https://user-images.githubusercontent.com/20315934/106247795-015eee80-624b-11eb-8cb6-1791ac44355e.png)

**Comment by abcdsxg** [comment]
使用生成环境 watch 就正常，不太清楚是哪里的问题。

NODE_ENV=production taro build --type qq --watch

**Comment by pcdotfan** [comment]
> 使用生成环境 watch 就正常，不太清楚是哪里的问题。
> 
> NODE_ENV=production taro build --type qq --watch

这个问题我也困扰了好久……正在跟进

**Comment by chareice** [comment]
大兄弟这个问题有进展吗？

**Comment by pcdotfan** [comment]
> 大兄弟这个问题有进展吗？

可以尝试一下 `v1.1.0` 版本，有问题再反馈。
