### ISSUE TITLE
在tailwind.src.css文件中的引入，之前还有什么步骤吗？

### ISSUE THREAD

**Issue by DanileQin** [pcdotfan/taro-plugin-tailwind#8]
![image](https://user-images.githubusercontent.com/34501848/106413004-f5aa3c80-6483-11eb-8295-88d448000b46.png)

步骤：/src/tailwind.src.css 之前步骤都是一样的，但是直接按照这个内容引入的话，会报错说找不到。请问是还有步骤被省略了吗？

**Comment by pcdotfan** [comment]
可以看一下项目的 `example` 能不能正常跑起来，如果不行贴一下报错哈

**Comment by DanileQin** [comment]
一、index.tsx 文件代码
```
      <View className="p-6 max-w-sm mx-auto bg-white rounded-xl shadow-md flex items-center space-x-4">
        <View className="flex-shrink-0">
          <Image className="**h-6 w-12**" src={themeImg} />
        </View>
        <View>
          <View className="text-xl font-medium text-red">ChitChat</View>
          <p className="text-gray-500">You have a new message!</p>
        </View>
      </View>
```
Image 中设置了 h-6  w-12 但是看起来不生效。


二、在 tailwind.src.css 中
![image](https://user-images.githubusercontent.com/34501848/106418604-b97dd880-6491-11eb-8b50-378f92ac0e80.png)

三、运行效果图
![image](https://user-images.githubusercontent.com/34501848/106418638-ca2e4e80-6491-11eb-8be1-13b79f2c0482.png)

**Comment by pcdotfan** [comment]
![image](https://user-images.githubusercontent.com/3370745/106422066-e08bd880-6498-11eb-8c93-f5f26ab19109.png)
我使用示例项目测试没有复现出问题，可以尝试一下重新编译或者以 `NODE_ENV=production taro build --type weapp --watch` 启动项目

**Comment by DanileQin** [comment]
我试安装下 taro-tailwindcss 和 taro-tailwind 的方式就可以啦。
