### ISSUE TITLE
Taro v3.4.2 Cannot find module 'windicss-webpack-plugin'

### ISSUE THREAD

**Issue by yanbowe** [pcdotfan/taro-plugin-tailwind#81]
taro升级到v3.4.2报错Cannot find module 'windicss-webpack-plugin'，我需要额外安装windicss-webpack-plugin插件吗
![image](https://user-images.githubusercontent.com/43030980/155649133-7316c2c3-63c0-44c8-8b17-bca74349f01c.png)
项目依赖为1.2.6
![image](https://user-images.githubusercontent.com/43030980/155649334-0b65ffbd-ec38-42f4-af8c-f9cf5a4446e4.png)

**Comment by pcdotfan** [comment]
请尝试 [v1.2.7](https://github.com/pcdotfan/taro-plugin-tailwind/releases/tag/v1.2.7)

**Comment by yanbowe** [comment]
> 请尝试 [v1.2.7](https://github.com/pcdotfan/taro-plugin-tailwind/releases/tag/v1.2.7)

谢谢，已经成功了
