### ISSUE TITLE
最新版的有问题，编译出的css 中带有星号通配符

### ISSUE THREAD

**Issue by towry** [pcdotfan/taro-plugin-tailwind#83]
我在package.json里是这样声明这个依赖的：`^1.1.7`，所以在最新的安装中，npm 安装了 1.2.8 版本的 taro-plugin-tailwind，然后构建后发现 app.wxss 中包含星号通配符，导致开发者工具报错。

然后我就固定了版本为 1.1.7，再次构建后，这个问题就没有了。

**Comment by wangcheng2005** [comment]
也遇到了同样的问题. 生成的app.wxss文件中包含星号通配符,导致报错.
/* windicss layer base */
*, ::before, ::after {
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
  border-width: 0;
  border-style: solid;
  border-color: #e5e7eb;
}
* {
  --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
  --tw-ring-offset-width: 0;
  --tw-ring-offset-color: #fff;
  --tw-ring-color: rgba(59, 130, 246, 0.5);
  --tw-ring-offset-shadow: 0 0 #0000;
  --tw-ring-shadow: 0 0 #0000;
  --tw-shadow: 0 0 #0000;
}
恢复至1.1.7解决.

**Comment by pcdotfan** [comment]
> 也遇到了同样的问题. 生成的app.wxss文件中包含星号通配符,导致报错. /* windicss layer base */ *, ::before, ::after { -webkit-box-sizing: border-box; box-sizing: border-box; border-width: 0; border-style: solid; border-color: #e5e7eb; }
> 
> * {
>   --tw-ring-inset: var(--tw-empty,/_!_/ /_!_/);
>   --tw-ring-offset-width: 0;
>   --tw-ring-offset-color: #fff;
>   --tw-ring-color: rgba(59, 130, 246, 0.5);
>   --tw-ring-offset-shadow: 0 0 #0000;
>   --tw-ring-shadow: 0 0 #0000;
>   --tw-shadow: 0 0 #0000;
>   }
>   恢复至1.1.7解决.

可以开一个复现仓库吗？我这本地测试没有问题

**Comment by towry** [comment]
将 taro 依赖升级到最新版本后，没有出现这个问题了。
