### ISSUE TITLE
taro-plugin-unocss

### ISSUE THREAD

**Issue by transtone** [pcdotfan/taro-plugin-tailwind#84]
作者有空写一个 unocss 的插件吗？
https://github.com/unocss/unocss/tree/main/packages/webpack

**Comment by pcdotfan** [comment]
有兴趣可以自己实现一个哈，我之前测试 `@unocss/webpack` 可以直接用在 Taro 项目上，不需要做额外配置。

**Comment by transtone** [comment]
好的，我测试一下，如果可以直接用，就用不着做成插件了。
