### ISSUE TITLE
windi.css怎么生存的？

### ISSUE THREAD

**Issue by gezichenshan** [pcdotfan/taro-plugin-tailwind#85]
按照步骤一步步来，但是并不知道windi.css是怎么来的呀？

**Comment by pcdotfan** [comment]
可以看一下 [windicss-webpack-plugin](https://github.com/windicss/windicss-webpack-plugin) 里 `plugin.ts` 的实现，使用时只需要 `import 'windi.css'` 就可以了，不需要真的存在这一文件
